name: Build and Publish

# Controls when the action will run. Triggers the workflow on push to the "cinnamon" branch.
on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: "${{ github.actor }}"
  DOCKER_PASSWORD: "${{ secrets.GITHUB_TOKEN }}"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Required to publish Docker containers
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install pngquant gifsicle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      # We will do everything on the same Gradle task to avoid Gradle executing tasks that it was already executed in a previous step
      # (Example: Compiling everything again when publishing the Docker container)
      # We don't use the "jib" task due to https://github.com/GoogleContainerTools/jib/issues/4301
      - name: Build and Publish with Gradle
        env:
          # GitHub Actions has 7GBs of available RAM for workers, so let's bump it a bit up!
          GRADLE_OPTS: -Xmx4096m -Xms4096m
          ORG_GRADLE_PROJECT_PerfectDreamsUsername: ${{ secrets.PERFECTDREAMS_REPO_USERNAME }}
          ORG_GRADLE_PROJECT_PerfectDreamsPassword: ${{ secrets.PERFECTDREAMS_REPO_PASSWORD }}
        run: ./gradlew build publish -Dcommit.hash=${{ github.sha }} -Dbuild.id=${{ github.run_number }} --scan --no-daemon